version: '3'
services:
  website:
    container_name: secondary_primary
    image: dckr.hamresan.app/proxy-secondary:latest
    network_mode: "host"
    volumes:
      - /etc/nginx/stream:/etc/nginx/stream


