---

- hosts: nodes
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded

    - name: Creates directory
      file:
        path: /etc/nginx/stream
        state: directory
        owner: ubuntu
        mode: 0775

    - name: Install pip
      apt:
        name: python-pip
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded

    - name: Install python-setuptools
      apt:
        name: python-setuptools
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded

    - name: Install inotify python package
      pip:
        name: inotify
        executable: pip2



    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/aliinejad/arvan-internship-fianl-project.git'
        dest: /tmp/git

    - name: Copy nginx config to server
      copy:
        src: /tmp/git/ansible/req/nginx.conf
        dest: /etc/nginx/
        owner: ubuntu
        group: ubuntu
        mode: 0755
        remote_src: yes


    - name: reload service httpd, in all cases
      systemd:
        name: nginx
        state: reloaded

    - name: Copy python app to server
      copy:
        src: /tmp/git/reload.py
        dest: /usr/local/bin
        owner: ubuntu
        group: ubuntu
        mode: 0755
        remote_src: yes

    - name: Copy systemd service file to server
      copy:
        src: /tmp/git/ansible/req/reload.service
        dest: /etc/systemd/system
        owner: ubuntu
        remote_src: yes

    - name: just force systemd to reread configs (2.4 and above)
      systemd: daemon_reload=yes


    - name: enable and start reload servce
      systemd:
        name: reload.service
        state: started
        enabled: True
