---

- hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks:

    - include_tasks: docker_tasks.yml

    - name: Creates directory
      file:
        path: /etc/nginx/stream
        state: directory
        owner: ubuntu
        mode: 0775

    - name: Install lsyncd
      apt:
        name: lsyncd
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/aliinejad/arvan-internship-fianl-project.git'
        dest: /tmp/git



    - name: Create a master proxy container
      docker_container:
        name: master_proxy
        image: test
        state: started
        volumes:
          - /etc/nginx/stream:/code
        network_mode: host
        tty: yes 
        interactive: yes 
