---

- hosts: nodes
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks:

    - include_tasks: docker_tasks.yml

    - name: Creates directory
      file:
        path: /etc/nginx/stream
        state: directory
        owner: ubuntu
        mode: 0775

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/aliinejad/arvan-internship-fianl-project.git'
        dest: /tmp/git

    - name: Install python-docker
      apt:
        name: python-docker
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded


    - name: Create a master secondary container
      docker_container:
        name: secondary_proxy
        image: madmad99/proxy-secondary
        state: started
        volumes:
          - /etc/nginx/stream:/etc/nginx/stream
        network_mode: host
        tty: yes 
        interactive: yes 

