---

- hosts: nodes
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh

  tasks:

    - include_tasks: docker_tasks.yml

    - name: Creates directory
      file:
        path: /etc/nginx/stream
        state: directory
        owner: ubuntu
        mode: 0775

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/aliinejad/arvan-internship-fianl-project.git'
        dest: /tmp/git

    - name: Install python-docker
      apt:
        name: python-docker
        state: present
        update_cache: true
      retries: 3
      delay: 10
      register: result
      until: result is succeeded


    - name: Install or upgrade docker-compose
      get_url: 
        url : "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: >
        docker_compose_current_version is not defined
        or docker_compose_current_version is version(docker_compose_version, '<')

    - name: Creates compose  directory
      file:
        path: /opt/compose
        state: directory
        owner: ubuntu
        mode: 0775

    - name: Copy compose 
      copy:
        src: /tmp/git/ansible/req/secondary-compose.yaml
        dest: /opt/compose
        owner: ubuntu
        group: ubuntu
        mode: 0755
        remote_src: yes

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: dckr.hamresan.app
        username: hamresan
        password: MWVkZGYzMmJmNzFiYmIxNjhiN2RiNmQw
        reauthorize: yes
 

    - name: run docker compose
      command: docker-compose -f /opt/compose/secondary-compose.yaml up -d 
